### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Stalker-moment** [barokatu/viddown-ssyt#1]
![image](https://github.com/barokatu/viddown-ssyt/assets/118105588/7d247196-046f-426a-bbf6-e0f81155cf74)

**Comment by barokatu** [comment]
Sorry for the issue, after I checking the old back-end/REST API got down, and you can deploy your own back end using this project:
https://github.com/Sansekai/ssyoutube-api

so change the request url to you own back-end host url
